; Adafruit Feather M0 + RFM69HCW (868 MHz)
; https://www.adafruit.com/product/3178

[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
monitor_speed = 115200
lib_deps =
    epsilonrt/RadioHead@^1.122.1

upload_protocol = sam-ba
; Set your port if auto-detect fails:
; upload_port = /dev/serial/by-id/usb-Adafruit_Feather_M0_...
